@myhost = http://localhost:8080
@namespace = api
@baseurl = {{myhost}}/{{namespace}}

### 1. health endpoint test
GET {{baseurl}}/healthz

# @lang=lua
> {%
print(response.status.code == 200)
%}

### 6. Add User-1
POST {{baseurl}}/users

{
  "email": "mloneusk@example.co"
}

# @lang=lua
> {%
local status_check = response.status.code == 201
local content_type_check = response.headers["content-type"][1] == "application/json"
local body = response.body
local body_check_1 = string.find(body, "id") ~= nil
local body_check_2 = string.find(body, "created_at") ~= nil
local body_check_3 = string.find(body, "updated_at") ~= nil
local body_check_4 = vim.json.decode(response.body).email == "mloneusk@example.co"
print(status_check, content_type_check, body_check_1, body_check_2, body_check_3, body_check_4)
%}

### 7. Add User-2
POST {{baseurl}}/users

{
  "email": "dackjorsey@example.co"
}

# @lang=lua
> {%
local status_check = response.status.code == 201
local content_type_check = response.headers["content-type"][1] == "application/json"
local body = response.body
local body_check_1 = string.find(body, "id") ~= nil
local body_check_2 = string.find(body, "created_at") ~= nil
local body_check_3 = string.find(body, "updated_at") ~= nil
local body_check_4 = vim.json.decode(response.body).email == "dackjorsey@example.co"
print(status_check, content_type_check, body_check_1, body_check_2, body_check_3, body_check_4)
%}

### 8. Invalid User
POST {{baseurl}}/users

{
  "email": "bad-email-address"
}

# @lang=lua
> {%
print(
  response.status.code == 400,
  vim.json.decode(response.body).error == "Invalid email address"
)
%}

### 8.1 Test chirp-creation (assuming user doesn't exist already)
POST {{baseurl}}/users

{
  "email": "saul@bettercall.com"
}


# @lang=lua
> {%
local status_check = response.status.code == 201
local content_type_check = response.headers["content-type"][1] == "application/json"
local body = response.body
local body_check_1 = string.find(body, "id") ~= nil
local body_check_2 = string.find(body, "created_at") ~= nil
local body_check_3 = string.find(body, "updated_at") ~= nil
local body_check_4 = vim.json.decode(response.body).email == "saul@bettercall.com"
print(status_check, content_type_check, body_check_1, body_check_2, body_check_3, body_check_4)
client.global.set("userID", vim.json.decode(response.body).id)
%}

### 8.2 Test chirp-creation (assuming user doesn't exist already)
POST {{baseurl}}/chirps

{
  "body": "If you're committed enough, you can make any story work.",
  "user_id": "{{userID}}"
}
