@myhost = http://localhost:8080
@namespace = api
@baseurl = {{myhost}}/{{namespace}}

### 1. health endpoint test
GET {{baseurl}}/healthz

# @lang=lua
> {%
print(response.status.code == 200)
%}

### 2. Invalid User creation - bad email
POST {{baseurl}}/users

{
  "email": "bad-email-address",
  "password": "password"
}

# @lang=lua
> {%
print(
  response.status.code == 400,
  vim.json.decode(response.body).error == "Invalid email address"
)
%}

### 3. Invalid User creation - bad password (too long)
POST {{baseurl}}/users

{
  "email": "valid@domain.co",
  "password": "passwordpasswordpasswordpasswordpasswordpasswordpasswordpasswordpasswordpasswordpassword"
}

# @lang=lua
> {%
print(
  response.status.code == 400,
  vim.json.decode(response.body).error == "password too long"
)
%}

### 4. Add User-1
POST {{baseurl}}/users

{
  "email": "mloneusk@example.co",
  "password": "password"
}

# @lang=lua
> {%
local status_check = response.status.code == 201
local content_type_check = response.headers["content-type"][1] == "application/json"
local body = response.body
local body_check_1 = string.find(body, "id") ~= nil
local body_check_2 = string.find(body, "created_at") ~= nil
local body_check_3 = string.find(body, "updated_at") ~= nil
local body_check_4 = vim.json.decode(response.body).email == "mloneusk@example.co"
print(status_check, content_type_check, body_check_1, body_check_2, body_check_3, body_check_4)
%}

### 5. Add User-2
POST {{baseurl}}/users

{
  "email": "dackjorsey@example.co",
  "password": "password"
}

# @lang=lua
> {%
local status_check = response.status.code == 201
local content_type_check = response.headers["content-type"][1] == "application/json"
local body = response.body
local body_check_1 = string.find(body, "id") ~= nil
local body_check_2 = string.find(body, "created_at") ~= nil
local body_check_3 = string.find(body, "updated_at") ~= nil
local body_check_4 = vim.json.decode(response.body).email == "dackjorsey@example.co"
print(status_check, content_type_check, body_check_1, body_check_2, body_check_3, body_check_4)
%}

### 6.1 Test chirp-creation (assuming user doesn't exist already)
POST {{baseurl}}/users

{
  "email": "saul@bettercall.com",
  "password": "password"
}


# @lang=lua
> {%
local status_check = response.status.code == 201
local content_type_check = response.headers["content-type"][1] == "application/json"
local body = response.body
local body_check_1 = string.find(body, "id") ~= nil
local body_check_2 = string.find(body, "created_at") ~= nil
local body_check_3 = string.find(body, "updated_at") ~= nil
local body_check_4 = vim.json.decode(response.body).email == "saul@bettercall.com"
print(status_check, content_type_check, body_check_1, body_check_2, body_check_3, body_check_4)
client.global.set("userID", vim.json.decode(response.body).id)
%}

### 6.2 Test chirp-creation (assuming user doesn't exist already)
POST {{baseurl}}/chirps

{
  "body": "If you're committed enough, you can make any story work.",
  "user_id": "{{userID}}"
}

# @lang=lua
> {%
print(response.status.code == 201)
%}

### 6.3 Test chirp-creation (assuming user doesn't exist already)
POST {{baseurl}}/chirps

{
  "body": "I once told a woman I was Kevin Costner, and it worked because I believed it.",
  "user_id": "{{userID}}"
}

# @lang=lua
> {%
client.global.set("chirpID", vim.json.decode(response.body).id)
%}

### 9. Get Chirps for all users
GET {{baseurl}}/chirps


# @lang=lua
> {%
local status_check = response.status.code == 200
print(status_check)
%}

### 10. Get Chirp by ID
GET {{baseurl}}/chirps/{{chirpID}}

# @lang=lua
> {%
local status_check = response.status.code == 200
local body_check = vim.json.decode(response.body).body == "I once told a woman I was Kevin Costner, and it worked because I believed it."
print(status_check, body_check)
%}

### 11.1 Auth Login check (create the user to test it's login, assuming it
#doesn't exist already)
POST {{baseurl}}/users

{
  "email": "saul@bettercall.com",
  "password": "password"
}

# @lang=lua
> {%
print(response.status.code == 200)
%}

### 11.2 Auth Login check (create the user to test it's login, assuming it
#doesn't exist already)
POST {{baseurl}}/login

{
  "email": "saul@bettercall.com",
  "password": "password"
}

# @lang=lua
> {%
print(response.status.code == 200)
%}
