@myhost = http://localhost:8080
@namespace = app
@baseurl = {{myhost}}/{{namespace}}

### 1. 404 on root path
GET {{myhost}}/

# @lang=lua
> {%
print(response.status.code == 404)
%}

### 2. fetch the app's index.html
GET {{baseurl}}/

# @lang=lua
> {%
local status_code_check = response.status.code == 200
local body_check = string.find(response.body, "Welcome to Chirpy") ~= nil
print(status_code_check, body_check)
%}

### 3. fetch the app's assets page
GET {{baseurl}}/assets

# @lang=lua
> {%
local status_code_check = response.status.code == 200
local body_check = string.find(
          response.body,
"<pre>\
<a href=\"logo.png\">logo.png</a>\
</pre>"
        ) ~= nil
print(status_code_check, body_check)
%}

### 4. fetch the app's logo.png
GET {{baseurl}}/assets/logo.png

# @lang=lua
> {%
local status_code_check = response.status.code == 200
local content_type_check = response.headers["content-type"][1] == "image/png"
print(status_code_check, content_type_check)
%}
